// const API = {
//   students: "http://localhost:5000/v1/student/",
//   student: "http://localhost:5000/v1/student/:studentId",
//   colleges: "http://localhost:5000/v1/college/",
//   college: "http://localhost:5000/v1/college/:collegeId",
//   collegeStudent: "http://localhost:5000/v1/student/college/:collegeId",
//   collegeByState: "http://localhost:5000/v1/college/state/:stateId",
//   collegeByLocation: "http://localhost:5000/v1/college/location/:locationId",
//   collegeChart: "http://localhost:5000/v1/college/chart/pie",
//   collegeCourseChart: "http://localhost:5000/v1/college/chart/pie/course",
//   login: "http://localhost:5000/v1/login",
//   registration: "http://localhost:5000/v1/login/registration",
//   auth: "http://localhost:5000/v1/login/auth",
//   categories: "http://localhost:5000/v1/categories",
//   states: "http://localhost:5000/v1/states",
//   categoryDashboard: "http://localhost:5000/v1/categories/dashboard",
//   services: "http://localhost:5000/v1/services",
//   getServiceById: "http://localhost:5000/v1/services/:serviceId",
//   servicesChart: "http://localhost:5000/v1/services/chart",
//   sendOtp: "http://localhost:5000/v1/login/otp",
//   verifyOtp: "http://localhost:5000/v1/login/verifyOtp",
//   changePassword: "http://localhost:5000/v1/login/changePassword",
//   addCategory: "http://localhost:5000/v1/categories/addCategory",
//   categoryImage: "http://localhost:5000/v1/categoryImages/:id",
//   addService: "http://localhost:5000/v1/services/addService",
//   getAllCity: "http://localhost:5000/v1/city",
// };
const API = {
  students: "v1/student/",
  student: "v1/student/:studentId",
  colleges: "v1/college/",
  college: "v1/college/:collegeId",
  collegeStudent: "v1/student/college/:collegeId",
  collegeByState: "v1/college/state/:stateId",
  collegeByLocation: "v1/college/location/:locationId",
  collegeChart: "v1/college/chart/pie",
  collegeCourseChart: "v1/college/chart/pie/course",
  login: "v1/login",
  registration: "v1/login/registration",
  auth: "v1/login/auth",
  categories: "/v1/categories",
  states: "/v1/states",
  categoryDashboard: "/v1/categories/dashboard",
  services: "/v1/services",
  getServiceById: "/v1/services/:serviceId",
  servicesChart: "/v1/services/chart",
  sendOtp: "/v1/login/otp",
  verifyOtp: "/v1/login/verifyOtp",
  changePassword: "/v1/login/changePassword",
  addCategory: "/v1/categories/addCategory",
  categoryImage: "/v1/categoryImages/:id",
  addService: "/v1/services/addService",
  getAllCity: "/v1/city",
};
export default API;
